# steering:
#   ros__parameters:
#     d_velocity: 1000
#     d_acceleration: 10000
#     d_limits: 6000
#     d_current: 5000

steering:
  ros__parameters:
    d_velocity: 1000
    d_acceleration: 1000
    d_limits: 5000
    d_current: 2500
