# steering_controller_node:
#   ros__parameters:
#     d_velocity: 1000
#     d_acceleration: 10000
#     d_limits: 6000
#     d_current: 5000

steering_actuator_node:
  ros__parameters:
    velocity: 5000
    acceleration: 1000
    centre_angle: -2.0
    max_position: 8500
    Kp: 10.0
    Ki: 0.0
    Kd: 0.0
