# steering_controller_node:
#   ros__parameters:
#     d_velocity: 1000
#     d_acceleration: 10000
#     d_limits: 6000
#     d_current: 5000

steering_controller_node:
  ros__parameters:
    velocity: 1000
    velocity_centering: 50
    acceleration: 300
    Kp: 40.0
    Ki: 0.0
    Kd: 0.0
