# steering_controller_node:
#   ros__parameters:
#     d_velocity: 1000
#     d_acceleration: 10000
#     d_limits: 6000
#     d_current: 5000

steering_actuator_node:
  ros__parameters:
    velocity: 5000
    velocity_centering: 20
    acceleration: 1000
    acceleration_centering: 50
    centre_range: 0.5
    Kp: 10.0
    Ki: 0.0
    Kd: 0.0
