# steering_controller_node:
#   ros__parameters:
#     d_velocity: 1000
#     d_acceleration: 10000
#     d_limits: 6000
#     d_current: 5000

steering_controller_node:
  ros__parameters:
    velocity: 100
    acceleration: 100
    Kp: 40.0
    Ki: 3.0
    Kd: 4.0
