steering_actuator_node:
  ros__parameters:
    velocity: 5000
    acceleration: 1000
    max_position: 8500
    steering_pid:
      p: 10.0
      i: 1.0
      d: 0.0
      i_clamp_max: 8500.0
      i_clamp_min: -8500.0
      antiwindup: true
