<?xml version="1.0"?>
<robot name="qev3" xmlns:xacro="http://ros.org/wiki/xacro">
    <!-- =================================================================== -->
    <!--                         Properties (in METERS)                      -->
    <!-- =================================================================== -->
    <xacro:property name="chassis_width" value="0.4" />
    <xacro:property name="chassis_length" value="1.5" />
    <xacro:property name="chassis_height" value="0.2" />

    <xacro:property name="wheel_diameter" value="0.4318" />
    <xacro:property name="wheel_thickness" value="0.05" />

    <xacro:property name="velodyne_diameter" value="0.1" />
    <xacro:property name="velodyne_height" value="0.0869" />

    <xacro:property name="zed2i_width" value="0.17525" />
    <xacro:property name="zed2i_length" value="0.0373" />
    <xacro:property name="zed2i_height" value="0.03025" />



    <!-- =================================================================== -->
    <!--                             Materials                               -->
    <!-- =================================================================== -->
    <material name="chassis">
        <color rgba="0.93 0.46 0.14 1"/>
    </material>

    <material name="wheel">
        <color rgba="0 0 0 1"/>
    </material>

    <material name="sensor">
        <color rgba="0.85 0.85 0.85 1"/>
    </material>

    <!-- =================================================================== -->
    <!--                           Links & Joints                            -->
    <!-- =================================================================== -->

    <!-- Base link (chassis) -->
    <link name="base_link">
        <visual>
            <origin xyz="0 0 ${chassis_height/2}" rpy="0 0 0" />
            <geometry>
                <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
            </geometry>
            <material name="chassis"/>
        </visual>
    </link>

    <!-- Wheels -->
    <xacro:macro name="wheel" params="name side direction">
        <!-- side is 1, -1 for left, right -->
        <!-- direction is 1, -1 for front, back -->
        <link name="${name}_wheel">
            <visual>
                <origin xyz="0 0 0" rpy="${pi/2} 0 0" />
                <geometry>
                    <cylinder radius="${wheel_diameter/2}" length="${wheel_thickness}"/>
                </geometry>
                <material name="wheel"/>
            </visual>
        </link>
        <joint name="${name}_wheel_joint" type="continuous">
            <axis xyz="0 1 0" rpy="0 0 0" />
            <parent link="base_link"/>
            <child link="${name}_wheel"/>
            <origin xyz="${direction*chassis_length/3} ${side*chassis_width/2 + 0.1*side} ${chassis_height / 2}" rpy="0 0 0"/>
        </joint>
    </xacro:macro>

    <xacro:wheel name="fl" side="1" direction="1"/>
    <xacro:wheel name="fr" side="-1" direction="1"/>
    <xacro:wheel name="bl" side="1" direction="-1"/>
    <xacro:wheel name="br" side="-1" direction="-1"/>

    <!-- Velodyne -->
    <link name="velodyne">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
                <cylinder radius="${velodyne_diameter/2}" length="${velodyne_height}"/>
            </geometry>
            <material name="sensor"/>
        </visual>
    </link>
    <joint name="velodyne_joint" type="fixed">
        <parent link="base_link"/>
        <child link="velodyne"/>
        <origin xyz="${chassis_length/2 + velodyne_diameter/2} 0 ${velodyne_height/2}" rpy="0 0 0"/>
    </joint>

    <!-- ZED2i -->
    <link name="zed2i">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
                <box size="${zed2i_length} ${zed2i_width} ${zed2i_height}"/>
            </geometry>
            <material name="sensor"/>
        </visual>
    </link>
    <joint name="zed2i_joint" type="fixed">
        <parent link="base_link"/>
        <child link="zed2i"/>
        <origin xyz="-0.05 0 ${2*chassis_height}" rpy="0 0 0"/>
    </joint>

</robot>
