recorder:
  ros__parameters:
    use_sim_time: false
    record:
      all_topics: true
      all_services: true
      all_actions: true
      is_discovery_disabled: false
      topic_polling_interval:
        sec: 0
        nsec: 10000000
      include_hidden_topics: true
      ignore_leaf_topics: false
      start_paused: false
      # exclude_topics: ["exclude_topic", "other_exclude_topic"]

    storage:
      uri: "~/repos/bags"
      storage_id: "mcap"
      max_cache_size: 20000000
