site_name: QUT Motorsport - Driverless
repo_name: QUT-Motorsport/QUTMS_Driverless
repo_url: https://github.com/QUT-Motorsport/QUTMS_Driverless

theme: readthedocs

nav:
  - Home: README.md
  - Using the Repository: GitHub.md
  - Setup:
    - Docker with WSL: Docker_Install.md
    - Formula Student Driverless Simulator: FSDS_Dev.md
  - Development:
    - LiDAR Perception in Python: Lidar_Perception_Dev.md
    - YOLOv5 Perception in Python: YOLOv5_Dev.md
