[tool.black]
line-length = 120

[tool.isort]
line_length = 120
profile = "black"
sections = [
    "FUTURE",
    "STDLIB",
    "THIRDPARTY",
    "TESTING",
    "FIRSTPARTY",
    "LOCALFOLDER",
    "TYPING",
]
default_section = "THIRDPARTY"
known_typing = ["typing", "mypy_extensions", "typing_extensions"]
known_testing = ["testing"]
force_sort_within_sections = "true"
force_to_top = "true"
