[tool.black]
line-length = 120

[tool.isort]
line_length = 120
profile = "black"
sections = [
    "STDLIB",
    "THIRDPARTY",
    "FUTURE",
    "ROS",
    "MESSAGES",
    "SRVS",
    "TESTING",
    "FIRSTPARTY",
    "LOCALFOLDER",
    "TYPING",
]
default_section = "THIRDPARTY"
known_thirdparty = ["launch"]
known_ros = ["rclpy", "message_filters", "cv_bridge", "rosidl_runtime_py"]
known_messages = ["*.msg"]
known_srvs = ["*.srv"]
known_testing = ["testing"]
known_srvs = ["*.srv"]
known_typing = ["typing", "mypy_extensions", "typing_extensions"]
force_sort_within_sections = "true"
force_to_top = "true"
src_paths = ["src/**"]
