controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    ackermann_steering_controller:
      type: tricycle_steering_controller/TricycleSteeringController

    ackermann_steering_direct_controller:
      type: tricycle_steering_controller/TricycleSteeringController

    drive_pid_controller:
      type: pid_controller/PidController

    steering_pid_controller:
      type: pid_controller/PidController

joint_state_broadcaster:
  ros__parameters: {}

ackermann_steering_controller:
  ros__parameters:
    reference_timeout: 2.0
    in_chained_mode: true
    front_steering: true
    open_loop: false
    velocity_rolling_window_size: 10
    position_feedback: false
    use_stamped_vel: true
    rear_wheels_names: [drive_pid_controller/rear_left_wheel_joint, drive_pid_controller/rear_right_wheel_joint]
    front_wheels_names: [steering_pid_controller/virtual_front_wheel_joint]
    rear_wheels_state_names: [rear_left_wheel_joint, rear_right_wheel_joint]
    front_wheels_state_names: [virtual_front_wheel_joint]
    wheelbase: 1.535
    wheel_track: 1.400
    front_wheels_radius: 0.2032
    rear_wheels_radius: 0.2032

    # Command limits
    linear:
      x:
        has_velocity_limits: true
        max_velocity: 25.0
        min_velocity: -15.0
        has_acceleration_limits: true
        max_acceleration: 10.0
        min_acceleration: -10.0
    angular:
      z:
        has_velocity_limits: true
        max_velocity: 2.0
        min_velocity: -2.0

drive_pid_controller:
  ros__parameters:
    type: pid_controller/PidController
    dof_names:
      - rear_left_wheel_joint
      - rear_right_wheel_joint
    command_interface: effort
    reference_and_state_interfaces: ["velocity"]
    gains:
      rear_left_wheel_joint: {p: 30.0, i: 0.5, d: 0.0, antiwindup: true, i_clamp_max: 5.0, i_clamp_min: -5.0}
      rear_right_wheel_joint: {p: 30.0, i: 0.5, d: 0.0, antiwindup: true, i_clamp_max: 5.0, i_clamp_min: -5.0}

steering_pid_controller:
  ros__parameters:
    type: pid_controller/PidController
    dof_names:
      - virtual_front_wheel_joint
    command_interface: position
    reference_and_state_interfaces: ["position"]
    gains:
      virtual_front_wheel_joint: {p: -7050.0, i: -470.0, d: 0.0, antiwindup: true, i_clamp_max: 2350.0, i_clamp_min: -2350.0}

ackermann_steering_direct_controller:
  ros__parameters:
    reference_timeout: 2.0
    in_chained_mode: false
    front_steering: true
    open_loop: false
    velocity_rolling_window_size: 10
    position_feedback: false
    use_stamped_vel: true
    rear_wheels_names: [rear_left_wheel_joint, rear_right_wheel_joint]
    front_wheels_names: [virtual_front_wheel_joint]
    rear_wheels_state_names: [rear_left_wheel_joint, rear_right_wheel_joint]
    front_wheels_state_names: [virtual_front_wheel_joint]
    wheelbase: 1.535
    wheel_track: 1.400
    front_wheels_radius: 0.2032
    rear_wheels_radius: 0.2032

    # Command limits
    linear:
      x:
        has_velocity_limits: true
        max_velocity: 25.0
        min_velocity: -15.0
        has_acceleration_limits: true
        max_acceleration: 10.0
        min_acceleration: -10.0
    angular:
      z:
        has_velocity_limits: true
        max_velocity: 2.0
        min_velocity: -2.0
