lidar_detector_node:
  ros__parameters:
    log_level: DEBUG
    # Max range of points to process (metres)
    lidar_range: 25
    min_range: 3

    # LiDAR and Cone params
    cone_size: 0.10
    cone_height: 0.30

    # DBSCAN Parameters
    # Neighbourhood Scan Size
    epsilon: 1.2  # > 1m otherwise clusters smaller non-cones objects
    # Number of points required to form a neighbourhood
    min_points: 2  # 2-3 allows for long-range cone detection
