<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
  <xacro:macro name="chassis" params="base_frame display_car">
    <!-- Base Frame -->
    <link name="${base_frame}"/>

    <!-- Chassis -->
    <joint name="${chassis_link}_joint" type="fixed">
      <parent link="${base_frame}"/>
      <child link="${chassis_link}"/>
      <!-- Wheel height off ground -->
      <origin xyz="0 0 ${wheel_diameter/2}"
              rpy="0 0 0"/>
      <axis xyz="1 0 0"/>
    </joint>

    <link name="${chassis_link}">
      <visual>
        <xacro:if value="${display_car}">
          <origin xyz="0 0 0" rpy="0 0 0"/>
          <geometry>
            <mesh filename="file://$(find vehicle_urdf)/meshes/lando.dae"/>
          </geometry>
        </xacro:if>
        <xacro:unless value="${display_car}">
          <origin xyz="0.3 0 0.2" rpy="0 0 0"/>
          <geometry>
            <box size="2.5 0.7 0.6"/>
          </geometry>
          <material name="orange"/>
        </xacro:unless>
      </visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
    </link>
  </xacro:macro>

  <!-- Wheels -->
  <xacro:macro name="wheels">   <!--Template for the wheels -->

    <!-- Wheel description -->
    <xacro:macro name="wheel" params="lr_prefix fr_prefix">
      <link name="${lr_prefix}_${fr_prefix}_wheel">
        <visual>
          <origin xyz="0 0 0" rpy="${degrees_90} 0 0"/>
          <geometry>
            <cylinder radius="${wheel_diameter / 2}" length="${wheel_width}"/>
          </geometry>
          <material name="black"/>
        </visual>
      </link>
    </xacro:macro>

    <!-- Front and rear wheel descriptions -->
    <!-- Description of how a front wheel is connected to the chassis -->
    <xacro:macro name="front_wheel" params="lr_prefix lr_reflect">
      <link name="${lr_prefix}_steering_hinge"/>
      <joint name="${lr_prefix}_steering_hinge_joint" type="fixed">
        <origin xyz="${wheelbase / 2}
                     ${lr_reflect * ((chassis_width - wheel_width) / 2)}
                     0"
                rpy="0 0 0"/>
        <parent link="${chassis_link}"/>
        <child link="${lr_prefix}_steering_hinge"/>
        <axis xyz="0 0 1"/>
        <limit lower="${-1*steering_limit}" upper="${steering_limit}" effort="10000000" velocity="1000000"/>
      </joint>

      <joint name="front_${lr_prefix}_wheel_joint" type="fixed">
        <origin xyz="0 0 0"
                rpy="0 0 0"/>
        <parent link="${lr_prefix}_steering_hinge"/>
        <child link="${lr_prefix}_front_wheel"/>
        <axis xyz="0 1 0"/>
        <limit lower="0" upper="0" effort="10000000" velocity="1000000"/>
      </joint>

      <xacro:wheel lr_prefix="${lr_prefix}" fr_prefix="front"/>
    </xacro:macro>

    <!-- Description of how a rear wheel is connected to the chassis -->
    <xacro:macro name="rear_wheel" params="lr_prefix lr_reflect">
      <joint name = "virtual_rear_wheel_joint" type = continuous>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <parent link="${chassis_link}"/>
        <child link="${lr_prefix}_rear_wheel"/>
        <axis xyz="0 1 0"/>
      </joint>

      <joint name="rear_${lr_prefix}_wheel_joint" type="fixed">
        <origin xyz="${-1 * wheelbase / 2}
                     ${lr_reflect * ((chassis_width - wheel_width) / 2)}
                     0"
                rpy="0 0 0"/>
        <parent link="${chassis_link}"/>
        <child link="${lr_prefix}_rear_wheel"/>
        <axis xyz="0 1 0"/>
        <limit lower="0" upper="0" effort="10000000" velocity="1000000"/>
      </joint>

      <xacro:wheel lr_prefix="${lr_prefix}" fr_prefix="rear"/>
    </xacro:macro>

    <!-- Add the wheels -->
    
    <!-- left_front_wheel -->
    <xacro:front_wheel lr_prefix="left" lr_reflect="1"/> 

    <!-- right_front_wheel -->
    <xacro:front_wheel lr_prefix="right" lr_reflect="-1"/>

    <!--  left_rear_wheel -->
    <xacro:rear_wheel lr_prefix="left" lr_reflect="1" />


    <xacro:rear_wheel lr_prefix="right" lr_reflect="-1" />
  </xacro:macro>
</robot>
