<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
  <xacro:macro name="chassis" params="base_frame display_car">

    <!-- Base Frame -->
    <link name="${base_frame}"/>

    <!-- Chassis -->
    <joint name="${chassis_link}_joint" type="fixed">
      <parent link="${base_frame}"/>
      <child link="${chassis_link}"/>
      <!-- Wheel height off ground -->
      <origin xyz="0 0 ${wheel_diameter/2}" rpy="0 0 0"/>
      <axis xyz="1 0 0"/>
    </joint>

    <link name="${chassis_link}">
      <visual>
        <xacro:if value="${display_car}">
          <origin xyz="0 0 0" rpy="0 0 0"/>
          <geometry>
            <mesh filename="file://$(find vehicle_urdf)/meshes/lando.dae"/>
          </geometry>
        </xacro:if>
        <xacro:unless value="${display_car}">
          <origin xyz="0.3 0 0.2" rpy="0 0 0"/>
          <geometry>
            <box size="2.5 0.7 0.6"/>
          </geometry>
          <material name="orange"/>
        </xacro:unless>
      </visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="1.0"/>
        <inertia ixx="0.1" ixy="0.0" ixz="0.0" iyy="0.1" iyz="0.0" izz="0.1"/>
      </inertial>
    </link>
  </xacro:macro>

  <!-- Wheels -->
  <xacro:macro name="wheels">

    <!-- Virtual wheel for immitation purposes -->
    <xacro:macro name="virtual_conponents">
      <link name="virtual_rear_wheel">
        <visual>
          <origin xyz="0 0 0" rpy="${PI/2} 0 ${PI/2}"/>
          <geometry>
            <cylinder length="0.01" radius="${wheel_diameter / 2}"/>
          </geometry>
          <material name="invisible"/>
        </visual>
        <inertial>
          <origin xyz="0 0 0" rpy="0 0 0"/>
          <mass value="0.1"/>
          <inertia ixx="0.01" ixy="0.0" ixz="0.0" iyy="0.01" iyz="0.0" izz="0.01"/>
        </inertial>
      </link>
      <link name="virtual_front_wheel">
        <visual>
          <origin xyz="0 0 0" rpy="${PI/2} 0 ${PI/2}"/>
          <geometry>
            <cylinder length="0.01" radius="${wheel_diameter / 2}"/>
          </geometry>
          <material name="invisible"/>
        </visual>
        <inertial>
          <origin xyz="0 0 0" rpy="0 0 0"/>
          <mass value="0.1"/>
          <inertia ixx="0.01" ixy="0.0" ixz="0.0" iyy="0.01" iyz="0.0" izz="0.01"/>
        </inertial>
      </link>

      <joint name="virtual_rear_wheel_joint" type="continuous">
        <parent link="${chassis_link}"/>
        <child link="virtual_rear_wheel"/>
        <origin xyz="-${wheelbase/2} 0 -${base_height/2}" rpy="0 0 ${PI/2}"/>
        <axis xyz="1 0 0"/>
        <limit effort="100.0" velocity="100.0"/>
        <dynamics damping="0.2"/>
      </joint>

      <joint name="virtual_front_wheel_joint" type="revolute">
        <parent link="${chassis_link}"/>
        <child link="virtual_front_wheel"/>
        <origin xyz="${wheelbase/2} 0 -${base_height/2}" rpy="0 0 ${PI/2}"/>
        <axis xyz="0 0 1"/>
        <limit lower="-0.4" upper="0.4" effort="100.0" velocity="0.0"/>
        <dynamics damping="0.2"/>
      </joint>
    </xacro:macro>



    <!-- Wheel description -->
    <xacro:macro name="wheel" params="lr_prefix fr_prefix">
      <link name="${lr_prefix}_${fr_prefix}_wheel">
        <visual>
          <origin xyz="0 0 0" rpy="${degrees_90} 0 0"/>
          <geometry>
            <cylinder radius="${wheel_diameter / 2}" length="${wheel_width}"/>
          </geometry>
          <material name="white"/>
        </visual>
        <inertial>
          <origin xyz="0 0 0" rpy="0 0 0"/>
          <mass value="0.1"/>
          <inertia ixx="0.01" ixy="0.0" ixz="0.0" iyy="0.01" iyz="0.0" izz="0.01"/>
        </inertial>
      </link>
    </xacro:macro>

    <!-- Front and rear wheel descriptions -->
    <!-- Description of how a front wheel is connected to the chassis -->
    <xacro:macro name="front_wheel" params="lr_prefix lr_reflect">
      <link name="${lr_prefix}_steering_hinge">
        <inertial>
          <origin xyz="0 0 0" rpy="0 0 0"/>
          <mass value="0.1"/>
          <inertia ixx="0.01" ixy="0.0" ixz="0.0" iyy="0.01" iyz="0.0" izz="0.01"/>
        </inertial>
      </link>

      <joint name="${lr_prefix}_steering_hinge_joint" type="revolute">
        <origin xyz="${wheelbase / 2}
                     ${lr_reflect * ((chassis_width - wheel_width) / 2)}
                     0" rpy="0 0 0"/>
        <parent link="${chassis_link}"/>
        <child link="${lr_prefix}_steering_hinge"/>
        <axis xyz="0 0 1"/>
        <mimic joint="virtual_front_wheel_joint" multiplier="1" offset="0"/>
        <limit lower="${-1*steering_limit}" upper="${steering_limit}" effort="10000000" velocity="1000000"/>
      </joint>

      <joint name="front_${lr_prefix}_wheel_joint" type="fixed">
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <parent link="${lr_prefix}_steering_hinge"/>
        <child link="${lr_prefix}_front_wheel"/>
        <axis xyz="0 1 0"/>
        <limit lower="0" upper="0" effort="10000000" velocity="1000000"/>
      </joint>

      <xacro:wheel lr_prefix="${lr_prefix}" fr_prefix="front"/>
    </xacro:macro>

    <!-- Description of how a rear wheel is connected to the chassis -->
    <xacro:macro name="rear_wheel" params="lr_prefix lr_reflect">
      <joint name="rear_${lr_prefix}_wheel_joint" type="continuous">
        <origin xyz="${-1 * wheelbase / 2}
                     ${lr_reflect * ((chassis_width - wheel_width) / 2)}
                     0" rpy="0 0 0"/>
        <parent link="${chassis_link}"/>
        <child link="${lr_prefix}_rear_wheel"/>
        <axis xyz="0 1 0"/>
        <!-- the real rear wheel joint should mimic the behaviour of the continuous virtual rear joint -->
        <mimic joint="virtual_rear_wheel_joint" multiplier="1" offset="0"/>
        <limit lower="0" upper="0" effort="10000000" velocity="1000000"/>
      </joint>

      <xacro:wheel lr_prefix="${lr_prefix}" fr_prefix="rear"/>
    </xacro:macro>

    <!-- ADDING VIRTUAL COMPONENTS -->
    <xacro:virtual_conponents/>

    <!-- ADD: -->
    <!-- Links: left_steering_hinge, left_steering_hinge, left_front_wheel, right_front_wheel -->
    <!-- Joints: right_steering_hinge_joint, left_steering_hinge_joint,  -->
    <!-- front_left_wheel_joint, front_right_wheel_joint-->
    <xacro:front_wheel lr_prefix="left" lr_reflect="1"/>
    <xacro:front_wheel lr_prefix="right" lr_reflect="-1"/>


    <!-- ADD: -->
    <!-- Links: left_rear_wheel, right_rear_wheel -->
    <!-- Joints: rear_left_wheel_joint, rear_right_wheel_joint,  -->
    <xacro:rear_wheel lr_prefix="left" lr_reflect="1" />
    <xacro:rear_wheel lr_prefix="right" lr_reflect="-1" />


  </xacro:macro>
</robot>
