<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
  <!-- QEV-3D parameters-->
  <xacro:property name="PI" value="3.1415926535897931"/>
  <xacro:property name="chassis_width" value="1.6"/>
  <xacro:property name="wheel_radius" value="0.5"/>
  <xacro:property name="wheel_width" value="0.2"/>
  <xacro:property name="wheelbase" value="1.580"/>
  <xacro:property name="base_height" value="0.3"/>
  <xacro:property name="base_width" value="0.6"/>
  <xacro:property name="chassis_link" default="chassis"/>
  <!--Chassis link name-->
  <xacro:property name="steering_limit" value="0.28"/>
  <xacro:property name="degrees_90" value="1.5708"/>
  <!-- 90 degrees in radians -->
  <material name="invisible">
    <color rgba="0 0 0 0"/>
  </material>

  <xacro:macro name="chassis" params="base_frame display_car">
    <!-- Base Frame -->
    <link name="${base_frame}"/>

    <!-- Chassis -->
    <joint name="${chassis_link}_joint" type="fixed">
      <parent link="${base_frame}"/>
      <child link="${chassis_link}"/>
      <!-- Wheel height off ground -->
      <origin xyz="0 0 ${wheel_radius}" rpy="0 0 0"/>
      <axis xyz="1 0 0"/>
    </joint>

    <link name="${chassis_link}">
      <visual>
        <xacro:if value="${display_car}">
          <origin xyz="0 0 0" rpy="0 0 0"/>
          <geometry>
            <mesh filename="file://$(find vehicle_urdf)/meshes/lando.dae"/>
          </geometry>
        </xacro:if>
        <xacro:unless value="${display_car}">
          <origin xyz="0.3 0 0.2" rpy="0 0 0"/>
          <geometry>
            <box size="2.5 0.7 0.6"/>
          </geometry>
          <material name="orange"/>
        </xacro:unless>
      </visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
    </link>
  </xacro:macro>

  <!-- Wheels -->
  <xacro:macro name="wheels">    <!--Template for the wheels -->

    <!-- Virtual wheel for immitation purposes -->
    <link name="virtual_rear_wheel">
      <visual>
        <origin xyz="0 0 0" rpy="${PI/2} 0 ${PI/2}"/>
        <geometry>
          <cylinder length="0.01" radius="${wheel_radius}"/>
        </geometry>
        <material name="invisible"/>
      </visual>
    </link>
    <link name="virtual_front_wheel">
      <visual>
        <origin xyz="0 0 0" rpy="${PI/2} 0 ${PI/2}"/>
        <geometry>
          <cylinder length="0.01" radius="${wheel_radius}"/>
        </geometry>
        <material name="invisible"/>
      </visual>
    </link>

    <joint name="virtual_rear_wheel_joint" type="continuous">
      <parent link="${chassis_link}"/>
      <child link="virtual_rear_wheel"/>
      <origin xyz="-${wheelbase/2} 0 -${base_height/2}" rpy="0 0 ${PI/2}"/>
      <axis xyz="1 0 0"/>
      <limit effort="100.0" velocity="100.0"/>
      <dynamics damping="0.2"/>
    </joint>

    <joint name="virtual_front_wheel_joint" type="revolute">
      <parent link="${chassis_link}"/>
      <child link="virtual_front_wheel"/>
      <origin xyz="${wheelbase/2} 0 -${base_height/2}" rpy="0 0 ${PI/2}"/>
      <axis xyz="0 0 1"/>
      <limit lower="-0.4" upper="0.4" effort="100.0" velocity="0.0"/>
      <dynamics damping="0.2"/>
    </joint>


    <!-- Wheel visualisation description -->
    <xacro:macro name="wheel" params="lr_prefix fr_prefix">
      <link name="${lr_prefix}_${fr_prefix}_wheel">
        <visual>
          <origin xyz="0 0 0" rpy="${degrees_90} 0 0"/>
          <geometry>
            <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
          </geometry>
          <material name="black"/>
        </visual>
      </link>
    </xacro:macro>

    <!-- Front and rear wheel descriptions -->
    <!-- Description of how a front wheel is connected to the chassis -->
    <xacro:macro name="front_wheel" params="lr_prefix lr_reflect">
      <!-- create a link for steering hinge -->
      <link name="${lr_prefix}_steering_hinge"/>

      <!-- create joint to connect corresponding {lr}_steering_hinge to the chassis -->
      <joint name="${lr_prefix}_steering_hinge_joint" type="fixed">
        <origin xyz="${wheelbase / 2}
                     ${lr_reflect * ((chassis_width - wheel_width) / 2)}
                     0" rpy="0 0 0"/>
        <parent link="${chassis_link}"/>
        <!-- connect to the chassis -->
        <child link="${lr_prefix}_steering_hinge"/>
        <!-- connect to the steering hinge -->
        <axis xyz="0 0 1"/>
        <!-- axis of rotation -->
        <limit lower="${-1*steering_limit}" upper="${steering_limit}" effort="10000000" velocity="1000000"/>
      </joint>




      <!-- create a joint connect the {lr}_steering_hinge to the {lr}_front_wheel -->
      <joint name="front_${lr_prefix}_wheel_joint" type="revolute">
        <!-- connect to the chassis -->
        <parent link="${chassis_link}"/>
        <!-- connect to the {lr}_front_wheel -->
        <child link="${lr_prefix}_front_wheel"/>

        <origin xyz="-${wheelbase/2} ${base_width/2} -${base_height/2}" rpy="0 0 ${PI/2}"/>
        <!-- axis of rotation -->
        <axis xyz="0 0 1"/>

        <limit lower="-0.4" upper="0.4" effort="1000.0" velocity="0"/>
        <dynamics damping="0.2"/>
        <mimic joint="virtual_front_wheel_joint" multiplier="1.0" offset="0.0"/>
      </joint>

      <!-- launch the macro to add the front wheel links pair -->
      <xacro:wheel lr_prefix="${lr_prefix}" fr_prefix="front"/>
    </xacro:macro>

    <!-- Description of how a rear wheel is connected to the chassis -->
    <xacro:macro name="rear_wheel" params="lr_prefix lr_reflect">

      <joint name="rear_${lr_prefix}_wheel_joint" type="continuous">
        <origin xyz="${-1 * wheelbase / 2}
                     ${lr_reflect * ((chassis_width - wheel_width) / 2)}
                     0" rpy="0 0 0"/>
        <parent link="${chassis_link}"/>
        <child link="${lr_prefix}_rear_wheel"/>
        <axis xyz="1 0 0"/>
        <dynamics damping="0.2"/>
        <limit effort="10000000" velocity="1000000"/>
        <mimic joint="virtual_rear_wheel_joint" multiplier="1.0" offset="0.0"/>
      </joint>


      <!-- Add the wheel -->
      <xacro:wheel lr_prefix="${lr_prefix}" fr_prefix="rear"/>
    </xacro:macro>



    <!-- Add the wheels -->

    <!-- left_front_wheel -->
    <xacro:front_wheel lr_prefix="left" lr_reflect="1"/>

    <!-- right_front_wheel -->
    <xacro:front_wheel lr_prefix="right" lr_reflect="-1"/>

    <!--  left_rear_wheel -->
    <xacro:rear_wheel lr_prefix="left" lr_reflect="1" />


    <xacro:rear_wheel lr_prefix="right" lr_reflect="-1" />
  </xacro:macro>
</robot>
