channels:
  - robostack-staging
  - conda-forge
dependencies:
  # ---------------------------------------------------------------------------
  # ROS Base Env deps (common across Jetson and ROScube)
  # ---------------------------------------------------------------------------
  - python=3.10
  - ros-humble-desktop
  - colcon-common-extensions
  - ca-certificates
  - openssl
  - compilers
  - cmake=3.18
  - pkg-config
  - make
  - ninja
  - numpy==1.23
  - typing-extensions # for some reason, not installed in base python?
  - tornado
  - colour
  - pip
variables:
  # fix for WSL RVIZ2
  LIBGL_ALWAYS_INDIRECT:
