FROM osrf/ros:galactic-desktop

RUN apt-get update && apt-get install -y --no-install-recommends \
    ros-galactic-plotjuggler-ros \
    # add more stuff here if needed
    && rm -rf /var/lib/apt/lists/

WORKDIR /fs_msgs_ws/src
RUN git clone https://github.com/FS-Driverless/fs_msgs.git --branch ros2 --depth=1

WORKDIR /fs_msgs_ws
RUN /bin/bash -c "source /opt/ros/$ROS_DISTRO/setup.bash; colcon build --packages-up-to fs_msgs"

WORKDIR /
