<?xml version="1.0"?>
<robot name="qev3" xmlns:xacro="http://ros.org/wiki/xacro">
    <!-- =================================================================== -->
    <!--                         Properties (in METERS)                      -->
    <!-- =================================================================== -->
    <xacro:property name="chassis_width" value="0.64" />
    <xacro:property name="chassis_length" value="2.51" />
    <xacro:property name="chassis_height" value="0.55" />

    <xacro:property name="wheel_diameter" value="0.381" />
    <xacro:property name="wheel_thickness" value="0.2" />

    <xacro:property name="velodyne_diameter" value="0.1" />
    <xacro:property name="velodyne_height" value="0.0869" />

    <xacro:property name="zed2i_width" value="0.17525" />
    <xacro:property name="zed2i_length" value="0.0373" />
    <xacro:property name="zed2i_height" value="0.03025" />

    <!-- =================================================================== -->
    <!--                             Materials                               -->
    <!-- =================================================================== -->
    <material name="wheel">
        <color rgba="0 0 0 1"/>
    </material>

    <material name="sensor">
        <color rgba="0.85 0.85 0.85 1"/>
    </material>

    <!-- =================================================================== -->
    <!--                           Links & Joints                            -->
    <!-- =================================================================== -->
    <!-- Base link (chassis) -->
    <link name="car">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
                <mesh filename="file://$(find vehicle_urdf)/meshes/lando.dae"/>
            </geometry>
            <material name="chassis"/>
        </visual>
    </link>

    <!-- Wheels -->
    <xacro:macro name="wheel" params="name loc">
        <!-- side is 1, -1 for left, right -->
        <!-- direction is 1, -1 for front, back -->
        <link name="${name}_wheel">
            <visual>
                <origin xyz="0 0 0" rpy="${pi/2} 0 0" />
                <geometry>
                    <cylinder radius="${wheel_diameter/2}" length="${wheel_thickness}"/>
                </geometry>
                <material name="wheel"/>
            </visual>
        </link>
        <joint name="${name}_wheel_joint" type="continuous">
            <axis xyz="0 1 0" rpy="0 0 0" />
            <parent link="car"/>
            <child link="${name}_wheel"/>
            <origin xyz="${loc}" rpy="0 0 0"/>
        </joint>
    </xacro:macro>

    <xacro:wheel name="fl" loc="0.67 -0.6 -0.05"/>
    <xacro:wheel name="fr" loc="0.67 0.6 -0.05"/>
    <xacro:wheel name="rl" loc="-0.68 -0.6 -0.05"/>
    <xacro:wheel name="rr" loc="-0.68 0.6 -0.05"/>

    <!-- Velodyne -->
    <link name="velodyne">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
                <cylinder radius="${velodyne_diameter/2}" length="${velodyne_height}"/>
            </geometry>
            <material name="sensor"/>
        </visual>
    </link>
    <joint name="velodyne_joint" type="fixed">
        <parent link="car"/>
        <child link="velodyne"/>
        <origin xyz="1.590 0 -0.15" rpy="0 0 0"/>
    </joint>

    <!-- ZED2i -->
    <link name="zed2i">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
                <box size="${zed2i_length} ${zed2i_width} ${zed2i_height}"/>
            </geometry>
            <material name="sensor"/>
        </visual>
    </link>
    <joint name="zed2i_joint" type="fixed">
        <parent link="car"/>
        <child link="zed2i"/>
        <origin xyz="-0.370 0 0.900" rpy="0 0 0"/>
    </joint>

    <link name="zed2i_left_camera_optical_frame">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
                <box size="${zed2i_length} ${zed2i_width} ${zed2i_height}"/>
            </geometry>
            <material name="sensor"/>
        </visual>
    </link>
    <joint name="frame_joint" type="fixed">
        <parent link="zed2i"/>
        <child link="zed2i_left_camera_optical_frame"/>
        <origin xyz="0 0.05 0" rpy="0 0 0"/>
    </joint>

</robot>
