channels:
  - robostack-experimental
  - conda-forge
dependencies:
  # ---------------------------------------------------------------------------
  # ROS Base Env deps
  # ---------------------------------------------------------------------------
  # tag below used for PYTHON_VERSION_OVERRIDE in Dockerfile.base
  ###PYTHON_VERSION###
  - python=3.9
  - ros-galactic-desktop
  - ros-galactic-rosidl-generator-c=2.2.1  # downgrade version for msg generation bug fix
  - ca-certificates
  - openssl
  - compilers
  - cmake=3.21
  - pkg-config
  - make
  - ninja
  - typing-extensions # for some reason, not installed in base python?
  - pip
  - pip:
    - colcon-common-extensions
    # colcon shell support
    - colcon-argcomplete
    - colcon-bash
    - colcon-zsh
variables:
  # fix for WSL RVIZ2
  LIBGL_ALWAYS_INDIRECT:
