<?xml version="1.0"?>
<package format="3">
  <!-- Deprecated and replaced by qutms_hw_interfaces and ros2_control_bringup -->
  <name>qev_controllers</name>
  <version>0.0.0</version>
  <description>Deprecated.</description>
  <maintainer email="team@qutmotorsport.com">Walden Leung</maintainer>
  <license>MIT</license>
  <buildtool_depend>ament_cmake</buildtool_depend>
  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
