FROM osrf/ros:galactic-desktop

# Docker config setup
ENV DEBIAN_FRONTEND=noninteractive
ENV SHELL /bin/bash
SHELL ["/bin/bash", "-c"]


# ==============================================================================
#                          Install apt packages
# ==============================================================================

RUN apt-get update && apt-get install -y --no-install-recommends \
    sudo \
    curl \
    nano \
    ca-certificates \
    git \
    # add more stuff here if needed
    && rm -rf /var/lib/apt/lists/


# ==============================================================================
#                           Set up a user using host UID
#    (this helps with file permissions when mounting folders into a container)
# ==============================================================================

ARG USERNAME
ARG HOST_UID
# dialout group is used for compatability with mac
ARG HOST_GROUP=dialout

# create user and set no password required
RUN useradd \
        -r \
        -m \
        -d /home/${USERNAME}/ \
        -u ${HOST_UID} \
        -g ${HOST_GROUP} \
        -G sudo,video,audio \
        ${USERNAME} && \
    echo ${USERNAME}:${USERNAME} | chpasswd && \
    echo "${USERNAME} ALL=NOPASSWD: ALL" >> /etc/sudoers.d/${USERNAME}


# ==============================================================================
#                          Install Dev Tools
# ==============================================================================

RUN apt-get update && apt-get install -y --no-install-recommends \
    python3-pip \
    nano \
    # add more stuff here if needed
    && rm -rf /var/lib/apt/lists/

# set python3 as python command
RUN ln -s /usr/bin/python3 /usr/bin/python

WORKDIR /home/$USERNAME

# ==============================================================================
#                         Install src Dependencies
# ==============================================================================

# make driverless workspace
RUN mkdir -p /home/${USERNAME}/driverless_ws/src && \
    chown -R ${USERNAME}:${HOST_GROUP} /home/${USERNAME}
WORKDIR /home/$USERNAME/driverless_ws

# copy in files and install dependencies
COPY --chown=${HOST_UID}:${HOST_GROUP} ./src /home/${USERNAME}/driverless_ws/src
RUN rosdep update && \
    apt-get update && \
    rosdep install -i --from-path src --skip-keys="zed_wrapper" -y --rosdistro galactic -y \
    && rm -rf /var/lib/apt/lists/

# ==============================================================================
#                           Add ROS entrypoint
# ==============================================================================
# setup entrypoint
COPY ./src/unreal_sim/galactic_entrypoint.sh /galactic_entrypoint.sh
ENTRYPOINT ["/galactic_entrypoint.sh"]
RUN echo "source /opt/ros/galactic/setup.bash" >> /home/$USERNAME/.bashrc

WORKDIR /tmp 

# vision_pipeline
COPY ./src/perception/lidar_pipeline/conda_requirements ./requirements.txt
RUN pip3 install -r requirements.txt
RUN rm -f ./requirements.txt

WORKDIR /home/$USERNAME/driverless_ws
USER ${USERNAME}

# run a build
# COPY --chown=${USERNAME}:${HOST_GROUP} ./src/ ./src
# RUN source /opt/ros/galactic/install/setup.bash; \
#     colcon build --symlink-install --packages-up-to \
#         lidar_pipeline \
#     && rm -rf ./src
