name: Build and Test
on:
  pull_request:
    branches: [ master ]
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out QUTMS Driverless
        uses: actions/checkout@v2.3.4
        with:
          submodules: recursive

      - name: 'Checking out eufs_msgs'
        uses: actions/checkout@v2.3.4
        with: 
          repository: QUT-Motorsport/eufs_sim

      - name: 'Checking out eufs_rviz_plugins'
        run: git clone https://gitlab.com/eufs/eufs_rviz_plugins.git

      - name: 'Checking out sbg_ros2_driver'
        uses: actions/checkout@v2.3.4
        with: 
          repository: SBG-Systems/sbg_ros2_driver

      - name: Building and testing
        uses: ichiro-its/ros2-ci@v1.0.0
        with:
          ros2-distro: humble
